[package]
name = "telegram-video-converter"
version = "0.1.0"
edition = "2024"
description = "Convert videos to Telegram Mobile compatible format"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
